name: CI/CD Pipeline tp

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Spring Boot JAR
        run: |
          cd springboot/app
          mvn clean package -DskipTests

      - name: Build and Push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./springboot/app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest

      - name: Build and Push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./angular-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/angular-app:latest

      - name: Start application with Docker Compose
        run: |
          docker compose up -d
          sleep 20

      - name: Check running containers
        run: docker ps
