name: Workflow CI Pipeline tp

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Connection a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Builder l’image Docker du backend
        uses: docker/build-push-action@v5
        with:
          context: ./springboot/app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/springboot-backend:latest
      - name: Builder l’image Docker du frontend
        uses: docker/build-push-action@v5
        with:
          context: ./angular-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/angular-frontend:latest
      - name: Lancer la commande docker compose
        run: docker compose up -d 
