name: CI spring angular 

on:
  push:
    branches:
    - main

env:
  DOCKER_USERNAME=${{vars.DOCKERHUB_USERNAME}}

jobs:
  # This workflow contains a single job called"build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: checkout code source 
      uses:  actions/checkout@v6
    
    - name: build & test spring boot
      run: |
        cd springboot/app
        chmod +x mvnw
        ./mvnw clean package 
        ./mvn clean verify 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build image spring 
      run: |
        docker build -t $DOCKER_USERNAME/spring-app .   /springboot/app
        docker push $DOCKER_USERNAME/spring-app

    - name: build image angular 
      run: |
        docker build -t $DOCKER_USERNAME/angular-app .   /angular-app
        docker push $DOCKER_USERNAME/angular-app

    - name: Run docker compose 
      run: |
        docker compose down 
        docker compose up -d 